### ISSUE TITLE
FrontEnd - Home Page - The Search functionality is not working

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#1] opened 2019-04-10 20:03 UTC
The Search functionality is not working

![image](https://user-images.githubusercontent.com/49487834/55909482-7972a500-5bdc-11e9-921c-4c9595bdd820.png)

**Comment by nadagouda** [comment] 2019-04-21 21:33
Fixed.

**Comment by NourhanYoussef** [comment] 2019-04-24 14:00
The search functionality is not working from myside as the access from strapi is not working and @M-Abuelatta is checking.

**Comment by norangamal** [comment] 2019-06-17 08:20
The issue is still exists.
When you search with word النوع for ex it gave me a blank page as below:
￼

**Comment by norangamal** [comment] 2019-06-17 08:20
![New Note](https://user-images.githubusercontent.com/51783494/59589130-8edae280-90e9-11e9-893b-100c0209343c.jpeg)

**Comment by abdelazizelsaman** [comment] 2019-08-14 13:43
![](https://github.trello.services/images/mini-trello-icon.png) [FrontEnd - In مكتبة الجهاز - The search is not working #38](https://trello.com/c/cQjpm5ZO/18-frontend-in-%D9%85%D9%83%D8%AA%D8%A8%D8%A9-%D8%A7%D9%84%D8%AC%D9%87%D8%A7%D8%B2-the-search-is-not-working-38)

**Comment by abdelazizelsaman** [comment] 2019-08-14 13:44
![](https://github.trello.services/images/mini-trello-icon.png) [FrontEnd - Home Page - The Search functionality is not working #1](https://trello.com/c/3C8rEYon/19-frontend-home-page-the-search-functionality-is-not-working-1)

**Comment by Omar-Handouk** [comment] 2019-08-18 11:48
Fixed in pull request #79, please retest

**Comment by OmarReda** [comment] 2019-09-04 11:30
Need to be closed the issue is solved.

**Closed** 2019-09-04 11:35 UTC
Labels: Needs Re-testing, State: Pending Testing, bug
